name: air_quality_dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - dash
  - plotly
  - ipykernel # only required for debugging
  - openpyxl
  - beautifulsoup4
  - lxml
  - pip # only required for debugging
